In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../DATA/Advertising.csv")

In [5]:
df.head(10)

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9
5    8.7   48.9       75.0    7.2
6   57.5   32.8       23.5   11.8
7  120.2   19.6       11.6   13.2
8    8.6    2.1        1.0    4.8
9  199.8    2.6       21.2   10.6

In [7]:
X = df.drop("sales", axis=1)

In [9]:
y = df["sales"]

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [15]:
X_validation, X_holdout_test, y_validation, y_holdout_test = train_test_split(X_test, y_test, test_size=0.5, random_state=101)

In [17]:
len(X_validation)

30

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [45]:
model = RandomForestRegressor(n_estimators=30, random_state=101)

In [47]:
model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=30, random_state=101)

In [49]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [51]:
validation_predictions = model.predict(X_validation)

In [53]:
validation_predictions

array([14.40333333,  5.47333333,  4.14      , 15.72666667, 11.66666667,
        9.93      , 10.83333333, 11.48      , 18.02      ,  7.60333333,
       10.9       , 21.44333333, 14.08333333,  7.53333333, 11.81333333,
        6.83      , 13.51      , 13.62      , 11.01333333,  7.99666667,
       12.53333333, 21.63      , 19.49      , 15.73      , 16.05666667,
       24.21666667, 20.17666667,  9.50666667, 14.50333333, 19.36333333])

In [55]:
np.sqrt(mean_squared_error(y_validation, validation_predictions))

0.8542009478215644

In [57]:
mean_absolute_error(y_validation, validation_predictions)

0.6575555555555552

In [59]:
df.describe()["sales"]

count    200.000000
mean      14.022500
std        5.217457
min        1.600000
25%       10.375000
50%       12.900000
75%       17.400000
max       27.000000
Name: sales, dtype: float64

In [63]:
holdout_predictions = model.predict(X_holdout_test)

In [67]:
holdout_predictions

array([10.98      ,  9.56666667, 11.74333333, 12.45      , 20.27      ,
        9.24      , 11.10333333, 18.71333333, 18.89666667,  9.63666667,
        6.38666667,  6.58      , 12.69      , 10.16      , 12.72      ,
       11.66666667, 12.71      , 19.21      , 24.64333333, 25.17      ,
        7.64      ,  9.64666667, 17.29      , 15.37      , 10.43666667,
       21.17666667,  9.82      ,  9.61      ,  8.49666667, 11.26333333])

In [69]:
mean_absolute_error(y_holdout_test, holdout_predictions)

0.5937777777777775

In [71]:
np.sqrt(mean_squared_error(y_holdout_test, holdout_predictions))

0.745323693040418

In [73]:
final_model = RandomForestRegressor(n_estimators=30, random_state=101)

In [75]:
final_model.fit(X, y)

RandomForestRegressor(n_estimators=30, random_state=101)

In [77]:
import joblib

In [79]:
joblib.dump(final_model, "my_final_model.pkl")

['my_final_model.pkl']

In [81]:
X.columns

Index(['TV', 'radio', 'newspaper'], dtype='object')

In [83]:
list(X.columns)

['TV', 'radio', 'newspaper']

In [85]:
joblib.dump(list(X.columns), "my_col_names.pkl")

['my_col_names.pkl']

In [87]:
new_cols = joblib.load("col_names.pkl")

In [89]:
new_cols

['TV', 'radio', 'newspaper']

In [91]:
loaded_model = joblib.load("my_final_model.pkl")

In [93]:
loaded_model

RandomForestRegressor(n_estimators=30, random_state=101)

In [95]:
loaded_model.predict([[230, 70, 57]])

C:\Users\honer\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([24.19666667])